### ISSUE TITLE
bboxarea.cxx calculation is incorrect for orthographic cameras

### ISSUE THREAD

**Issue by ghost** [erich666/jgt-code#4]
I am looking at a bug where the eye position is directly beneath a bounding box. So, the classifier in bboxarea.cxx uses the bottom of the bounding box to calculate the area. But the orthographic view direction is parallel to the bottom of the bounding box, so the area is calculated as 0.

I think for orthographic cameras, the view direction needs to be used for classifying the silhouette, not the eye position. I think the using the max/min based on the sign of the direction would work. Maybe something like this:

    int pos = ((dir[0] > 0) ?  1 : 0)   // 1 = left
            + ((dir[0] < 0) ?  2 : 0)   // 2 = right
            + ((dir[1] > 0) ?  4 : 0)   // 4 = bottom
            + ((dir[1] < 0) ?  8 : 0)   // 8 = top
            + ((dir[2] > 0) ? 16 : 0)   // 16 = front
            + ((dir[2] < 0) ? 32 : 0);  // 32 = back

**Comment by erich666** [comment]
Hi, Cleve! Thanks, I know what you mean, and yes, the direction is what you can use in this case. I've made a note in the code itself.

On another note, their code is a tiny bit inefficient. You really need a table of just 27 entries, not 64, and Eric Lengyel's implementation uses this; otherwise the idea's the same. See "Game Math Case Studies," http://www.terathon.com/gdc15_lengyel.pdf

**Comment by clevea** [comment]
I was actually looking at the implementation you did for LMV and it uses the 27 entry table. It took me a  some time to track this one down.

**Comment by erich666** [comment]
Sorry, I should have added a comment! Now you know my sources.
